/* AUTHENTICATION TYPES */
export const AUTHENTICATION_SIGN_IN = 'AUTHENTICATION_SIGN_IN';
export const AUTHENTICATION_SIGN_UP = 'AUTHENTICATION_SIGN_UP';
export const AUTHENTICATION_SIGN_OUT = 'AUTHENTICATION_SIGN_OUT';
export const AUTHENTICATION_RESEND_CODE = 'AUTHENTICATION_RESEND_CODE';
export const AUTHENTICATION_SET_USERNAME = 'AUTHENTICATION_SET_USERNAME';
export const AUTHENTICATION_FORGOT_PASSWORD = 'AUTHENTICATION_FORGOT_PASSWORD';
export const AUTHENTICATION_CHANGE_PASSWORD = 'AUTHENTICATION_CHANGE_PASSWORD';
export const AUTHENTICATION_CONFIRM_PASSWORD =
  'AUTHENTICATION_CONFIRM_PASSWORD';
export const AUTHENTICATION_CONFIRM_REGISTRATION =
  'AUTHENTICATION_CONFIRM_REGISTRATION';
